
# Source all files in ~/dotfiles/source/
function src() {
  local file
  if [[ "$1" ]]; then
    source "$HOME/dotfiles/source/$1.sh"
  else
    for file in ~/dotfiles/source/*; do
      source "$file"
    done
  fi
}
src

export PATH="/usr/local/bin:$PATH"

source "$HOME/dotfiles/link/bashrc_private"
